### ISSUE TITLE
Mongodb connection fail

### ISSUE THREAD

**Issue by fxcjahid** [cheatsnake/graphql-nodejs-server#1]
Hello,
I am new at graphql and Mongodb. 
I don't know how to connect with MongoDB.

![Screenshot555_1](https://github.com/cheatsnake/graphql-nodejs-server/assets/33903532/d550d9a1-dfa8-4853-9898-d179b545badd)

**Comment by cheatsnake** [comment]
> Hello, I am new at graphql and Mongodb. I don't know how to connect with MongoDB.
> 
> ![Screenshot555_1](https://user-images.githubusercontent.com/33903532/252132466-d550d9a1-dfa8-4853-9898-d179b545badd.png)

Hi.
You need to carefully read the [instructions on how to start this server](https://github.com/cheatsnake/graphql-nodejs-server#usage). In step 4 I mention that you need to create a `.env` file with the variable MONGODB_URL, which corresponds to the address of your MongoDB server (if you start your MongoDB server at local network it would be `mongodb://localhost:27017/your_db_name`)

You can find more info about MongoDB [here](https://github.com/cheatsnake/backend-cheats#mongodb) and about GraphQL [here](https://github.com/cheatsnake/backend-cheats#graphql).
